export { default as AiRobotIcon } from './icon-AiRobot.vue'
export {default as chatIcon} from './icon-chat.vue'
export {default as forumIcon} from './icon-forum.vue'
export {default as squareIcon} from './icon-square.vue'
export {default as shareIcon} from './icon-share.vue'
export {default as likeIcon} from './icon-like.vue'
export {default as messageIcon} from './icon-message.vue'
export {default as lanchIcon} from './icon-lanch.vue'
export {default as projectIcon} from './icon-project.vue'
export { default as EditorIcon } from './icon-editor.vue'
export { default as BanIcon } from './icon-ban.vue'
export { default as DeleteIcon } from './icon-delete.vue'
export {default as Editor2Icon} from './icon-editor2.vue'
export {default as UsersIcon} from './icon-users.vue'
export {default as Delete2Icon} from './icon-delete2.vue'
export {default as Editor3Icon} from './icon-editor3.vue'
export {default as Delete3Icon} from './icon-delete3.vue'
export {default as CourseManagementIcon} from './icon-courseManagement.vue'
export {default as CourseListIcon} from './icon-courseList.vue'
export {default as CourseLanchIcon} from './icon-courseLanch.vue'
export {default as NewsManagementIcon} from './icon-newsManagement.vue'
export {default as ApproveIcon} from './icon-approve.vue'
export {default as UnderReviewIcon} from './icon-underreview.vue'