export { default as AiRobotIcon } from './icon-AiRobot.vue'
export {default as chatIcon} from './icon-chat.vue'
export {default as forumIcon} from './icon-forum.vue'
export {default as squareIcon} from './icon-square.vue'
export {default as shareIcon} from './icon-share.vue'
export {default as likeIcon} from './icon-like.vue'
export {default as messageIcon} from './icon-message.vue'
export {default as lanchIcon} from './icon-lanch.vue'
export {default as projectIcon} from './icon-project.vue'
export { default as EditorIcon } from './icon-editor.vue'
export { default as BanIcon } from './icon-ban.vue'
export { default as DeleteIcon } from './icon-delete.vue'
export {default as Editor2Icon} from './icon-editor2.vue'
export {default as UsersIcon} from './icon-users.vue'
export {default as Delete2Icon} from './icon-delete2.vue'