export { default as AiRobotIcon } from './icon-AiRobot.vue'
export {default as chatIcon} from './icon-chat.vue'
export {default as forumIcon} from './icon-forum.vue'
export {default as squareIcon} from './icon-square.vue'
export {default as shareIcon} from './icon-share.vue'
export {default as likeIcon} from './icon-like.vue'
export {default as messageIcon} from './icon-message.vue'
export {default as lanchIcon} from './icon-lanch.vue'
export {default as projectIcon} from './icon-project.vue'